### ISSUE TITLE
Improvement: check for duplicates

### ISSUE THREAD

**Issue by Noki** [freifunk-berlin/bbb-configs#508]
It's easy to make careless mistakes, e.g. when copying a configuration. We should therefore implement checks that check for duplicates and throw an error if there are any.

- [x] prefix must be globally unique in all vlans across all networks.yml files (#942)
- [x] ipv6_prefix must be globally unique across all networks.yml files (#942)
- [x] ipv6_subprefix must be unique within a networks.yml file (#1095)
- [x] name of a vlan must be unique within a networks.yml file (#942)
