### ISSUE TITLE
Update everything to 23.05

### ISSUE THREAD

**Issue by pktpls** [freifunk-berlin/bbb-configs#595]
The following models are still on 22.03

- [x] glinet_gl-b1300
  - [x] ~~casa-kua~~ (location gone) - PR #614
- [x] mikrotik_routerboard-750gr3
  - [x] hds
  - [x] vaterhaus - PR #687
- [x] mikrotik_routerboard-760igs
  - [x] ~~f17~~  (location gone)
- [x] ubnt_nanostation-ac-loco
  - [x] wilgu10
  - [x] ~~gub37~~ (buggy device)
- [x] ubnt_nanostation_loco_m5_xm
  - [x] ~~strom~~ (not used there anymore)
- [x] ubnt_nanostation_m2_xm
  - [x] chris
  - [x] jup
  - [x] magda
  - [ ] manstein10 (only manstein10-m2-w.olsr missing, device in outage)
  - [x] mlk-nk
  - [ ] philmel
  - [x] segen
  - [x] vaterhaus
  - [ ] zwingli (only zwingli-ost-nf-2ghz.olsr missing, device is in outage)
- [x] ubnt_nanostation_m5_xm
  - [x] jup
  - [x] manstein10
  - [ ] zwingli (only zwingli-ost-nf-5ghz.olsr missing, device is in outage)
- [x] ubnt_rocket-5ac-lite
  - [x] gruni73
- [ ] ubnt_unifi-6-lite
  - [ ] scharni
- [x] ubnt_unifiac-lite
  - [x] zwingli
  - [x] ~~casa-kua~~ (location gone)
- [x] ubnt_unifiac-mesh
  - [x] kotti
  - [ ] dragonkiez - PR #707
    - [ ] dragonkiez-adlerhalle (misses flashing)
  - [x] weidenbaum-r0 (#915)
  - [x] funkigel (#928)
  - [ ] fardf (needs bbb-config-migratioin)
- [x] ubnt_unifiac-pro
  - [x] hds - #909

The following community locations require flashing of new firmware / hardware replacements

- [ ] agym
- [x] dragonkiez - on-site-appointment needed (see PR #707)
- [ ] suedblock (see https://github.com/freifunk-berlin/meta/issues/41)
- [ ] xdorf - booting old firmware from wrong partition - boot partition fix or on-site-appointment needed (see https://github.com/freifunk-berlin/meta/issues/44)

**Comment by pktpls** [comment]
22.03 will reach End-of-Life in April

**Comment by Petrella** [comment]
Isn't Ubiquiti nanostation m5 xm still on 22.03 officially?

**Comment by pktpls** [comment]
Yes, all the XM devices only have 32 MB RAM. We'll have to find tricks for that

**Comment by Petrella** [comment]
Will that be a problem? In the model files for devices like `model_ubnt_nanostation_m5xm` the `low_mem` option is set to true. So if you build an image luci and other things will not be present to make the image small. Do you have other concerns?

**Comment by pktpls** [comment]
22.03 EOL is Thursday next week

**Comment by pktpls** [comment]
The Unifi AC devices hds-ffraum and zwingli-dome-2 are on 23.05 now - the procedure is very simple: #909 

The dragonkiez and kotti devices can be upgraded the same way.

**Comment by pktpls** [comment]
The Nanostations upgrade fine - they only lose their overlay data, which is a very minor issue for us.

We're ready to remove 22.03

**Comment by pktpls** [comment]
We're done, 22.03 is already removed from main
